### ISSUE TITLE
Be more transparent about dynamic scoring

### ISSUE THREAD

**Issue by kevin-he-01** [acmucsd/ctfbot#13]
Make it so that teams don't have to [dig into our source code](https://github.com/acmucsd/ctfbot/blob/fb07e1dbf14208817e8184483c82df4b69590cc5/src/database/models/challenge.ts#L232) to find out how our dynamic scoring system works.
We should display our scoring formula somewhere (maybe as a page on [our website](https://sdc.tf) with a link to the page under the point values of every dynamically scored challenge) along with parameters such as initial points, minimum points, and number of solves to reach minimum.

This way people don't have to reverse engineer the parameters by solving math equations (it would be a nice CTF challenge though). A stretch goal is to implement a playground where participants can calculate their scores or place on the scoreboard based on hypothetical solves. We can even make a customizable scoreboard like [OOO's scoring-playground](https://github.com/o-o-overflow/scoring-playground).

**Comment by KNOXDEV** [comment]
We basically removed dynamic scoring so I'm closing this.
