### ISSUE TITLE
/invite process should use UserInteractions

### ISSUE THREAD

**Issue by KNOXDEV** [acmucsd/ctfbot#20]
Let's allow people to invite each other using User Interactions (new feature that allows right clicking on users).

[https://discord.com/developers/docs/interactions/application-commands#message-commands](https://discord.com/developers/docs/interactions/application-commands#message-commands)

Users can invite users from anywhere on Discord. Rather than require the person join the main server and THEN accept the ToS before joining another team, our invite system will handle it. 

**Case 1**: if the person is already in SDCTF as a team, they will be asked if they want to accept the invitation to join a new team and leave their old one. A button will be provided to accept the offer, ignoring is the same as rejecting. Once clicked, they will be given an invite to the Team Server.

**Case 2**: if the person has not accepted ToS, then when they accept the invitation, they will receive a follow up DM asking them to accept ToS, with buttons to accept it directly in the server. Once they accept the ToS, they will be invited to the Team Server.

**Comment by nerd** [comment]
i take full credit for this idea

**Comment by KNOXDEV** [comment]
Half-implemented. Currently using user interactions, but also using the old flow since it's less complex. I'll create another issue with the flow improvements for a later sprint.
